common:
  watch:
    - docker/common/Dockerfile
    - requirements/base.txt

  build:
    tag: {{ cookiecutter.repo_name }}:common
    dockerfile: docker/common/Dockerfile
    nocache: True
    rm: true

production:
  depends: common

  watch:
    - docker/production/Dockerfile
    - requirements/production.txt

  build:
    tag: {{ cookiecutter.repo_name }}:production
    dockerfile: docker/production/Dockerfile
    nocache: True
    rm: true

development:
  depends: production

  watch:
    - docker/development/Dockerfile

  build:
    tag: {{ cookiecutter.repo_name }}:development
    dockerfile: docker/development/Dockerfile
    nocache: True
    rm: true

local:
  depends: common

  watch:
    - docker/local/Dockerfile
    - requirements/local.txt

  build:
    tag: {{ cookiecutter.repo_name }}:local
    dockerfile: docker/local/Dockerfile
    nocache: True
    rm: true

testing:
  depends: common

  watch:
    - docker/testing/Dockerfile
    - requirements/local.txt

  build:
    tag: {{ cookiecutter.repo_name }}:testing
    dockerfile: docker/testing/Dockerfile
    nocache: True
    rm: true
